config/routes.rb
Rails.application.routes.draw do
  root to: "palettes#new"

  get :login,  to: "sessions#new"
  get :logout, to: "sessions#destroy"

  resources :sessions, only: [:create]
  resources :palettes, only: [:index, :show, :edit, :download]
  resources :colors,   only: [:create, :destroy]
  resources :users,    only: [:new, :create, :show, :edit, :update]

  # for .ase downloads
  resources :palettes do
  	member do
      get 'download'
    end
  end
end

app/models/authorization.rb
class Authorization
  include Guachiman

  def initialize(user)
    if @current_user = user
      user_authorization
    else
      guest_authorization
    end
  end

private

  def guest_authorization
    allow :sessions, %i[new create destroy]
    allow :palettes, %i[index new create show edit download]
    allow :colors,   %i[create destroy]
    allow :users,    %i[new create]
  end

  def user_authorization
    guest_authorization

    allow :users, %i[show edit update] do |user|
      @current_user.id == user.id
    end
  end
end

app/models/color.rb
class Color < ActiveRecord::Base
	belongs_to :palette
	acts_as_list scope: :palette

	validates :hex, presence: true, uniqueness: { scope: :palette_id }
end

app/models/palette.rb
class Palette < ActiveRecord::Base
	belongs_to :user

	belongs_to :parent,   class_name: self, foreign_key: :parent_id, counter_cache: :children_count
	has_many   :children, class_name: self, foreign_key: :parent_id, dependent: :destroy

	has_many :colors, -> { order("position ASC") }

	scope :roots, -> { where parent_id: nil }
	scope :leafs, -> { where children_count: 0 }

	def self.with_color(params)
		old_palette = find(params[:palette_id]) if params[:palette_id]
		new_palette = create user_id: params.delete(:user_id), parent_id: old_palette.try(:root_id)

		if old_palette
			old_palette.colors.each do |c|
				new_palette.colors.create(name: c.name, hex: c.hex, rgb: c.rgb, hsl: c.hsl, mixed: c.mixed)
			end
		end

		new_palette.colors.create(name: params[:name], hex: params[:hex], rgb: params[:rgb],
															hsl: params[:hsl], mixed: params[:mixed])

		new_palette
	end

	def without_color(hex, new_user_id = nil)
		new_palette = self.class.create parent_id: root_id, user_id: new_user_id

		colors.each do |c|
			new_palette.colors.create(name: c.name, hex: c.hex, rgb: c.rgb, hsl: c.hsl, mixed: c.mixed) unless c.hex == hex
		end

		new_palette
	end

	def root_id
		parent_id || id
	end
end

app/models/user.rb
require "bcrypt"

class User < ActiveRecord::Base
  validates :name,  presence: true
  validates :email, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def create
    @palette = Palette.with_color(color_params)

    respond_to do |format|
      format.html { redirect_to edit_palette_path(@palette) }
      format.json { render json: @palette }
    end
  end

  def destroy
    @color   = Color.find(params[:id])
    @palette = @color.palette.without_color(@color.hex)

    respond_to do |format|
      format.html { redirect_to edit_palette_path(@palette) }
      format.json { render json: @palette }
    end
  end

  private

  def color_params
    params.require(:color).permit(:palette_id, :name, :hex, :rgb, :hsl, :mixed)
  end
end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  before_action :set_palette, only: [:show, :edit, :download]

  def new;  end
  def edit; end

  def index
    @palettes = Palette.page(params[:page]).per(50).order("created_at DESC")
    render layout: false
  end

  def show
    respond_to do |format|
      format.html { render "show" }
      format.json { render json: @palette.colors }
    end
  end

  def download
    doc = ASE.new
    ase_palette = ASE::Palette.new(@palette.id.to_s)
    for color in @palette.colors
      ase_palette.add color.name, ASE::Color::RGB.from_hex(color.hex)
    end
    doc << ase_palette
    root = Rails.root.to_s
    file = ("#{root}/tmp/#{@palette.id}.ase").to_s
    doc.to_file(file)
    send_file file
  end

  private

  def set_palette
    @palette = Palette.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    user = User.where(email: params[:email]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    reset_session!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user

  def new
  end

  def create
    @user.assign_attributes user_params

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update user_params
      redirect_to @user
    else
      render :edit
    end
  end

private

  def set_user
    @user = params[:id].present? ? User.find(params[:id]) : User.new
  end

  def user_params
    params.require(:user).permit :name, :email, :password
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/palettes_helper.rb
module PalettesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_analytics.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-35016870-5', 'coleure.com');
    ga('send', 'pageview');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Coleure</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="//cloud.typography.com/6394892/653404/css/fonts.css" />
  <link id="dynamic-favicon" rel="shortcut icon" type="image/png" href="/favicon.png" />

  <%= javascript_include_tag 'application' %>
  <%= requirejs_include_tag 'coleure' %>
  <script>
    function getAuthToken() {
      return '<%= form_authenticity_token if protect_against_forgery? -%>';
    }
  </script>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-35016870-5', 'coleure.com');
    ga('send', 'pageview');
  </script>
</head>
<body id="app">

<%= yield %>

</body>
</html>

app/views/layouts/flatpage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag 'flatpage', media: 'all' %>
    <link rel="stylesheet" href="//cloud.typography.com/6394892/653404/css/fonts.css" />
    <link id="dynamic-favicon" rel="shortcut icon" type="image/png" href="/favicon.png" />
    <%= csrf_meta_tags %>
    <%= render "layouts/analytics" %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/palettes/_form.html.erb
<div id="compareModeDialog" class="mode-dialog">Select the color you want to compare with. <button id="exitCompareModeButton" class="secondary">Done</button></div>
<div id="mixModeDialog" class="mode-dialog">Select the color you want to mix with. <button id="exitMixModeButton" class="secondary">Done</button></div>
<h1 id="logo">
  <div class="text">Coleure</div>
  <div class="color-code">
    <a id="format_status"><span id="current_color_code">Hover any color</span>
      <svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <title>settings</title>
          <desc>Created with Sketch.</desc>
          <defs></defs>
          <g id="Page-2" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
              <path d="M19.3103448,12.1428571 L19.3103448,7.85714286 L16.4737931,7.85714286 C16.3227586,7.14285714 16.1117241,6.84142857 15.8475862,6.35142857 L17.8593103,4.29857143 L15.1289655,1.48714286 L13.1793103,3.57928571 C12.7055172,3.30357143 12.4137931,3.09571429 11.7241379,2.93857143 L11.7241379,0 L7.5862069,0 L7.5862069,2.93857143 C6.89655172,3.09571429 6.61931034,3.31285714 6.14482759,3.58785714 L4.16758621,1.50285714 L1.45586207,4.33071429 L3.47793103,6.35142857 C3.2137931,6.84142857 3.01310345,7.14285714 2.86206897,7.85714286 L0,7.85714286 L0,12.1428571 L2.86206897,12.1428571 C3.01310345,12.8571429 3.22275862,13.1464286 3.48827586,13.6385714 L1.47517241,15.6842857 L4.20551724,18.4928571 L6.14482759,16.3985714 C6.61931034,16.6728571 6.89655172,16.88 7.5862069,17.0371429 L7.5862069,20 L11.7241379,20 L11.7241379,17.0371429 C12.4137931,16.8807143 12.7034483,16.6628571 13.1793103,16.3885714 L15.1606897,18.4735714 L17.8751724,15.6457143 L15.8558621,13.6385714 C16.12,13.1464286 16.3227586,12.8571429 16.4737931,12.1428571 L19.3103448,12.1428571 L19.3103448,12.1428571 Z M9.66758621,13.37 C7.86413793,13.37 6.40275862,11.8557143 6.40275862,9.98785714 C6.40275862,8.12 7.86413793,6.60571429 9.66758621,6.60571429 C11.4703448,6.60571429 12.9317241,8.12 12.9317241,9.98785714 C12.9317241,11.8557143 11.4703448,13.37 9.66758621,13.37 L9.66758621,13.37 Z" id="settingsIcon" fill="#fff" sketch:type="MSShapeGroup"></path>
          </g>
      </svg></a>
    <div id="formatSettings" class="format-settings">
      <p><input id="clipboard_handler" readonly></input></p>
      <p>
        <button id="hex" class="set-format option join">HEX</button><button id="rgb" class="set-format option join">RGB</button><button id="hsl" class="set-format option join">HSL</button>
      </p>
      <p>
        Copy colors with <kbd>⌘ + C</kbd> or <kbd>Ctrl. + C</kbd>
      </p>
    </div>
  </div>
</h1>
<section id="palette">
  <div id="drop-message" class="dropzone">
    <div class="content">
      <p><i class="drop"></i><br>Drop your favorite<br>colors here.</p>
      <hr>
      <p><a href="/about" id="learnMoreLink">Learn more</a> about <br>the project.</p>
    </div>
  </div>
  <div class="share-button">
    <a class="button" id="shareButton" style="display: none;">Share</a>
  </div>
  <div id="palette_colors" class="clear b10"></div>
  <header class="select">
    <h1 class="subtitle">
      <span id="activePalette" class="active-palette">New</span>
    </h1>
    <h2>Palette</h2>
  </header>
</section>
<aside id="panels">
  <section id="inspector">
    <div id="preview">
      <div id="mixPanel">
        <button id="mixButton">Mix</button>
        <div id="mixControls">
            <input id="mixBalance" type="range" min="0.01" max="0.99" step="0.01" value="0.5">
          </div>
        <div id="mixResult">
          <span id="mixWeightA">50%</span>
          <span id="mixWeightB">50%</span>
          <button id="cancelMix" class="join">Cancel</button><button id="selectMix" class="color">Select</button>
        </div>
      </div>
      <div id="subjects" class="clear"></div>
    </div>
    <div id="tests" class="clear"></div>
  </section>
  <div class="the-rest">
    <section class="subject-options">
      <div class="column">
        <a id="compareModeButton" class="block-button"><i class="compare-icon"></i><br>Compare</a>
        <a id="editPanelButton" class="block-button"><i class="edit-icon"></i><br>Edit</a>
      </div>
      <div class="column">
        <a id="mixModeButton" class="block-button"><i class="mix-icon"></i><br>Mix</a>
        <a id="addToPaletteButton" class="block-button"><i class="add-to-palette-icon"></i><br>Add to Palette</a>
        <a id="removeButton" class="block-button"><i class="remove-icon"></i><br>Remove</a>
      </div>
    </section>
    <aside id="editPanel" class="color-editor">
      <section class="top">
        <header><label for="#">Code*</label></header>
        <div><input type="text" id="colorCode"></div>
      </section>
      <section>
        <header><label for="colorHueValue">H</label><input type="number" min="1" max="360" id="colorHueValue"></header>
        <div><input id="colorHueRange" type="range" min="1" max="360" step="1"></div>
      </section>
      <section>
        <header><label for="colorSaturationValue">S</label><input type="number" min="1" max="100" id="colorSaturationValue"></header>
        <div><input id="colorSaturationRange" type="range" min="0" max="100" step="1"></div>
      </section>
      <section>
        <header><label for="colorLightValue">L</label><input type="number" min="1" max="100" id="colorLightValue"></header>
        <div><input id="colorLightRange" type="range" min="0" max="100" step="1"></div>
      </section>
      <section>
        <header><label for="#">Name</label></header>
        <div><input type="text" id="colorName"></div>
      </section>
      <section class="push-header">
        <button id="exitEditPanelButton" class="secondary">Done</button>
      </section>
      <footer>* Only HEX allowed for now.</footer>
    </aside>
  </div>
</aside>
<section id="library">
  <nav id="user_menu">
    <a id="userMenuNewPaletteButton" class="block-button active"><i class="menu-plus"></i><br>New Palette</a>
    <a id="userMenuEditorButton" class="block-button active" style="display: none;"><i class="menu-panel"></i><br>Editor</a>
    <% if current_user %>
      <a class="block-button" href="/users/<%= current_user.id %>"><i class="menu-palettes"></i><br>My Palettes</a>
      <a class="block-button" href="#"><i class="menu-settings"></i><br>Settings</a>
      <a class="block-button" href="/logout"><i class="menu-exit"></i><br>Logout</a>
    <% else %>
      <a class="block-button" href="/login"><i class="menu-lock"></i><br>Login</a>
      <a class="block-button" href="/users/new"><i class="menu-user"></i><br>Sign Up<br><span id="appPrice" class="price">$10/yr</span></a>
    <% end %>
  </nav>
  <div id="colors"></div>
</section>

app/views/palettes/edit.html.erb
<%= render partial: "form" %>

app/views/palettes/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>All Palettes</title>
    <link rel="stylesheet" href="//cloud.typography.com/6394892/653404/css/fonts.css" />
    <link id="dynamic-favicon" rel="shortcut icon" type="image/png" href="/favicon.png" />
    <style>
      * {
        margin:0;
        padding:0;
        border:0;
        font-size:100%;
        vertical-align:baseline;
      }
      body {
        width: 60%;
        margin: 100px auto;
        font: 18px/1.5 "Gotham A", "Gotham B", "Gotham HTF", Futura, sans-serif;
        color: #fff;
        background: #232323;
      }
      img {
        max-width: 100%;
        margin-bottom: 2em;
      }
      .pagination {
        display: inline-block;
        padding: 0.25em 0.75em;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 16px;
        color: #333;
        background: #131313;
      }
      .pagination span {
        margin: 0 0.3em;
      }
      .pagination a {
        color: #fff;
      }
      .pagination a:hover {
        color: #eb0079;
      }
      a {
        text-decoration: none;
        color: #fff;
      }
      a.button {
        display: inline-block;
        vertical-align: middle;
        margin-left: 20px;
        padding: 0.5em 1em;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 12px;
        color: #232323;
        background: #fff;
      }
      a.button:hover {
        background: #111;
        color: #fff;
      }
      h1 {
        margin-bottom: 0.25em;
    font-size: 48px;
      }
      h2 {
        font-size: 16px;
      }
      .palette {
        display: block;
        overflow: hidden;
        padding-bottom: 15px;
        border-top: 2px solid #444;
        -webkit-column-break-inside: avoid;
        -moz-column-break-inside: avoid;
        -o-column-break-inside: avoid;
        column-break-inside: avoid;
        page-break-inside: avoid
      }
      .palette:hover {
        background: #444;
      }
      .color {
        width: 6.25%;
        padding-bottom: 6.25%;
        float: left;
      }
      .columns {
        margin-bottom: 2em;
        -webkit-columns: 4;
        -moz-columns: 4;
        -o-columns: 4;
        columns: 4;
      }
    </style>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-35016870-5', 'coleure.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <h1>Palettes <a href="/" class="button">Create Palette</a></h1>
    <div class="columns">
    <% @palettes.each do |palette| %>
      <a class="palette" href="/palettes/<%= palette.id %>">
        <h2>No. <%= palette.id %></h2>
        <% palette.colors.each do |color| %>
          <span class="color" style="background: #<%= color.hex %>;"></span>
        <% end %>
      </a>
    <% end %>
    </div>
    <p><%= paginate @palettes %></p>
  </body>
</html>

app/views/palettes/new.html.erb
<%= render partial: "form" %>

app/views/palettes/show.html.erb
<div class="palette-page">
  <h1 id="logo">
    <div class="text">No. <%= @palette.id %></div>
    <div class="color-code">
      <a id="format_status"><span id="current_color_code">Hover any color</span>
        <svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg">
            <title>settings</title>
            <desc>Created with Sketch.</desc>
            <defs></defs>
            <g id="Page-2" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
                <path d="M19.3103448,12.1428571 L19.3103448,7.85714286 L16.4737931,7.85714286 C16.3227586,7.14285714 16.1117241,6.84142857 15.8475862,6.35142857 L17.8593103,4.29857143 L15.1289655,1.48714286 L13.1793103,3.57928571 C12.7055172,3.30357143 12.4137931,3.09571429 11.7241379,2.93857143 L11.7241379,0 L7.5862069,0 L7.5862069,2.93857143 C6.89655172,3.09571429 6.61931034,3.31285714 6.14482759,3.58785714 L4.16758621,1.50285714 L1.45586207,4.33071429 L3.47793103,6.35142857 C3.2137931,6.84142857 3.01310345,7.14285714 2.86206897,7.85714286 L0,7.85714286 L0,12.1428571 L2.86206897,12.1428571 C3.01310345,12.8571429 3.22275862,13.1464286 3.48827586,13.6385714 L1.47517241,15.6842857 L4.20551724,18.4928571 L6.14482759,16.3985714 C6.61931034,16.6728571 6.89655172,16.88 7.5862069,17.0371429 L7.5862069,20 L11.7241379,20 L11.7241379,17.0371429 C12.4137931,16.8807143 12.7034483,16.6628571 13.1793103,16.3885714 L15.1606897,18.4735714 L17.8751724,15.6457143 L15.8558621,13.6385714 C16.12,13.1464286 16.3227586,12.8571429 16.4737931,12.1428571 L19.3103448,12.1428571 L19.3103448,12.1428571 Z M9.66758621,13.37 C7.86413793,13.37 6.40275862,11.8557143 6.40275862,9.98785714 C6.40275862,8.12 7.86413793,6.60571429 9.66758621,6.60571429 C11.4703448,6.60571429 12.9317241,8.12 12.9317241,9.98785714 C12.9317241,11.8557143 11.4703448,13.37 9.66758621,13.37 L9.66758621,13.37 Z" id="settingsIcon" fill="#fff" sketch:type="MSShapeGroup"></path>
            </g>
        </svg></a>
      <div id="formatSettings" class="format-settings">
        <p><input id="clipboard_handler" readonly></input></p>
        <p>
          <button id="hex" class="set-format option join">HEX</button><button id="rgb" class="set-format option join">RGB</button><button id="hsl" class="set-format option join">HSL</button>
        </p>
        <p>
          Copy colors with <kbd>⌘ + C</kbd> or <kbd>Ctrl. + C</kbd>
        </p>
      </div>
    </div>
  </h1>
  <div class="palette-options">
  	<%= link_to "Download (.ase)", download_palette_path, class: "button secondary" %><%= link_to "Edit", edit_palette_path, class: "button" %>
  </div>
  <div id="shared_palette_colors" class="active-palette">
  	<table class="fullscreen" cellspacing="0">
      <% for color in @palette.colors.reorder('position DESC') %>
        <tr>
          <td>
            <article
              class="item color"
              data-name="<%= color.name %>"
              data-hex="<%= color.hex %>"
              data-rgb="<%= color.rgb %>"
              data-hsl="<%= color.hsl %>"
              data-mixed="<%= color.mixed %>"
              data-origin="palette"
              style="background: #<%= color.hex %>;">
              <h1><% if color.mixed %><strong class="mix-mark">M</strong><% end %><%= color.name %></h1>
              <% if false %>
                <section class="color-info">
                  <h1><%= color.name %></h1>
                  <p>Top part of the flag.<br>Height: 2/4.</p><p><button class="secondary">Edit</button></p>
                </section>
              <% end %>
            </article>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/palettes/user.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>All Palettes</title>
    <link rel="stylesheet" href="//cloud.typography.com/6394892/653404/css/fonts.css" />
    <link id="dynamic-favicon" rel="shortcut icon" type="image/png" href="/favicon.png" />
    <style>
      * {
        margin:0;
        padding:0;
        border:0;
        font-size:100%;
        vertical-align:baseline;
      }
      body {
        width: 60%;
        margin: 100px auto;
        font: 18px/1.5 "Gotham A", "Gotham B", "Gotham HTF", Futura, sans-serif;
        color: #fff;
        background: #232323;
      }
      img {
        max-width: 100%;
        margin-bottom: 2em;
      }
      a {
        text-decoration: none;
        color: #fff;
      }
      a.button {
        display: inline-block;
        margin-top: 0.5em;
        padding: 0.5em 1em;
        text-transform: uppercase;
        font-weight: bold;
        font-size: 18px;
        color: #232323;
        background: #fff;
      }
      a.button:hover {
        background: #111;
        color: #fff;
      }
      h1 {
        margin-bottom: 0.25em;
    font-size: 48px;
      }
      h2 {
        font-size: 16px;
      }
      .palette {
        display: block;
        overflow: hidden;
        padding-bottom: 15px;
        border-top: 2px solid #444;
        -webkit-column-break-inside: avoid;
        -moz-column-break-inside: avoid;
        -o-column-break-inside: avoid;
        column-break-inside: avoid;
        page-break-inside: avoid
      }
      .palette:hover {
        background: #444;
      }
      .color {
        width: 6.25%;
        padding-bottom: 6.25%;
        float: left;
      }
      .columns {
        margin-bottom: 2em;
        -webkit-columns: 4;
        -moz-columns: 4;
        -o-columns: 4;
        columns: 4;
      }
    </style>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-35016870-5', 'coleure.com');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <h1>Palettes</h1>
    <div class="columns">
    <% @user.palettes.each do |palette| %>
      <a class="palette" href="/palettes/<%= palette.id %>/edit">
        <h2>No. <%= palette.id %></h2>
        <% palette.colors.each do |color| %>
          <span class="color" style="background: #<%= color.hex %>;"></span>
        <% end %>
      </a>
    <% end %>
    </div>
    <a href="/" class="button">Go back to Coleure</a>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for user do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="action">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/edit.html.erb
<%= render partial: "form", locals: { user: @user } %>

app/views/users/new.html.erb
<%= render partial: "form", locals: { user: @user } %>

app/views/users/show.html.erb
<%= @user.inspect %>